# Default values for cnj-tracing-backend-quarkus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ${docker.image.name}
  tag: ${project.version}
  pullPolicy: IfNotPresent

probes:
  readiness:
    path: /api/v1/probes/readiness
  liveness:
    path: /api/v1/probes/liveness

nameOverride: ""
fullnameOverride: ""
partOfOverride: "cnj-tracing"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  host: "${k8s.ingress.host}"
  paths: ["${k8s.ingress.path}"]

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 756Mi

# security configuration (Open ID Connect)
security:
  oidc:
    jwksUri: "https://iam.at41tools.k8s.aws.msgoat.eu/auth/realms/cloudtrain/protocol/openid-connect/certs"
    issuer: "https://iam.at41tools.k8s.aws.msgoat.eu/auth/realms/cloudtrain"

# downstream service configuration
downstream:
  rest:
    url: "http://cnj-tracing-downstream"

# persistence configuration (PostgreSQL)
persistence:
  postgres:
    database: cloudtrain
    host: cnj-tracing-resources-postgresql
    port: 5432
    secret:
      name: cnj-tracing-resources-postgres
      keys:
        user: postgresql-user
        password: postgresql-password

# metrics configuration
metrics:
  # enabled controls if pods are annotated for scraping
  enabled: true

# tracing configuration
tracing:
  enabled: true
  jaeger:
    agent:
      host: sys-tracing-jaeger-agent.sys-tracing
      port: 6831
    logSpans: true
